# docker-compose.yml
version: '3'
services:
  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer  # consumer.py를 위한 새로운 Dockerfile
    env_file:
      - .env.dev
  web:
    build: .
#    command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/_static
      - media_volume:/usr/src/app/_media
    expose:
      - 8000
    env_file:
      - ./.env.dev
  nginx:
    build: ./nginx
    volumes:
      - ./static:/usr/src/app/_static
      - media_volume:/usr/src/app/_media
    ports:
      - 80:80
    depends_on:
      - web
volumes:
    static_volume:
    media_volume: