# Generated by Django 4.2.6 on 2023-12-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
