# Generated by Django 4.2.6 on 2024-05-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_review', '0004_postmonthlypseudorec'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmonthlypseudorec',
            name='author',
            field=models.CharField(default='작성자추가', max_length=50),
        ),
        migrations.AddField(
            model_name='postmonthlypseudorec',
            name='tag1',
            field=models.CharField(default='Recommendation Model', max_length=50),
        ),
        migrations.AddField(
            model_name='postmonthlypseudorec',
            name='tag2',
            field=models.CharField(default='Tech', max_length=50),
        ),
    ]
