# Generated by Django 4.2.6 on 2024-05-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_review', '0005_postmonthlypseudorec_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmonthlypseudorec',
            name='subtitle',
            field=models.CharField(default='부제 작성', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='postmonthlypseudorec',
            name='title',
            field=models.CharField(default='제목 작성', max_length=100),
        ),
    ]
