# Generated by Django 4.2.6 on 2024-05-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_review', '0006_postmonthlypseudorec_subtitle_alter_post_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmonthlypseudorec',
            name='card_image',
            field=models.ImageField(blank=True, upload_to='paper_review/card_imgs', verbose_name='카드 이미지'),
        ),
    ]
