# Generated by Django 4.2.6 on 2024-05-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_review', '0007_postmonthlypseudorec_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmonthlypseudorec',
            name='month',
            field=models.CharField(default='203004', max_length=10),
        ),
    ]
