# Generated by Django 4.2.6 on 2024-06-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_review', '0008_postmonthlypseudorec_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmonthlypseudorec',
            name='author_image',
            field=models.ImageField(blank=True, upload_to='paper_review/author_imgs', verbose_name='카드 이미지'),
        ),
    ]
