# Generated by Django 4.2.6 on 2024-06-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_review', '0009_postmonthlypseudorec_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmonthlypseudorec',
            name='author_image',
            field=models.ImageField(blank=True, upload_to='paper_review/author_imgs', verbose_name='작성자 이미지'),
        ),
    ]
