# Generated by Django 5.1 on 2024-10-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_review', '0012_post_author_post_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='postmonthlypseudorec',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
