# Generated by Django 5.1 on 2024-10-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_review', '0013_alter_post_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='card_image',
            field=models.ImageField(blank=True, upload_to='paper_review/card_imgs', verbose_name='카드 이미지'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
