# Generated by Django 5.1 on 2024-10-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_review', '0014_post_card_image_alter_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author2',
            field=models.CharField(default='작성자2추가', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='author_image2',
            field=models.ImageField(blank=True, upload_to='paper_review/author_imgs', verbose_name='작성자2 이미지'),
        ),
    ]
