# Generated by Django 5.1 on 2024-11-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_review', '0015_post_author2_post_author_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmonthlypseudorec',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
