# Generated by Django 5.1 on 2025-02-14 07:20

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_review', '0017_post_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperTalkPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', markdownx.models.MarkdownxField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(default='작성자추가', max_length=50)),
                ('author_image', models.ImageField(blank=True, upload_to='paper_review/author_imgs', verbose_name='작성자 이미지')),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
