# Generated by Django 5.1 on 2025-02-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_review', '0019_alter_papertalkpost_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertalkpost',
            name='link1',
            field=models.URLField(blank=True, null=True, verbose_name='링크 1'),
        ),
        migrations.AddField(
            model_name='papertalkpost',
            name='link2',
            field=models.URLField(blank=True, null=True, verbose_name='링크 2'),
        ),
        migrations.AddField(
            model_name='papertalkpost',
            name='link3',
            field=models.URLField(blank=True, null=True, verbose_name='링크 3'),
        ),
    ]
