# Generated by Django 5.1 on 2025-02-25 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_review', '0020_papertalkpost_link1_papertalkpost_link2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='monthly_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paper_review.postmonthlypseudorec'),
        ),
    ]
