# Generated by Django 5.1 on 2025-02-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_review', '0022_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papertalkpost',
            name='author_image',
        ),
        migrations.AddField(
            model_name='papertalkpost',
            name='citation_count',
            field=models.PositiveIntegerField(default=0, verbose_name='인용 수'),
        ),
        migrations.AddField(
            model_name='papertalkpost',
            name='conference',
            field=models.CharField(default='Unknown Conference', max_length=100, verbose_name='학회'),
        ),
        migrations.AddField(
            model_name='papertalkpost',
            name='publication_month',
            field=models.PositiveIntegerField(default=1, verbose_name='출판 월'),
        ),
        migrations.AddField(
            model_name='papertalkpost',
            name='publication_year',
            field=models.PositiveIntegerField(default=2000, verbose_name='출판 연도'),
        ),
        migrations.AlterField(
            model_name='papertalkpost',
            name='author',
            field=models.CharField(default='저자 미상', max_length=50),
        ),
    ]
