# Generated by Django 5.1 on 2025-02-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_review', '0023_remove_papertalkpost_author_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papertalkpost',
            name='author',
            field=models.CharField(default='저자 미상', max_length=200),
        ),
    ]
