# Generated by Django 5.1 on 2025-12-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper_review", "0024_alter_papertalkpost_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="subcategory",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="postmonthlypseudorec",
            name="subcategory",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
