# Generated by Django 5.1 on 2025-12-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper_review", "0025_post_subcategory_postmonthlypseudorec_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="postmonthlypseudorec",
            name="category",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
