# Generated by Django 5.1 on 2025-12-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper_review", "0026_post_category_postmonthlypseudorec_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmonthlypseudorec",
            name="month_sort",
            field=models.IntegerField(
                default=203004, help_text="YYYYMM 형식의 정렬용 필드"
            ),
        ),
    ]
