# Generated by Django 5.1 on 2026-01-04 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_agent", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("analysis_date", models.DateField()),
                ("decision", models.CharField(max_length=50)),
                ("investment_plan", models.TextField()),
                ("risk_assessment", models.TextField(blank=True)),
                ("technical_analysis", models.TextField(blank=True)),
                ("fundamental_analysis", models.TextField(blank=True)),
                ("sentiment_analysis", models.TextField(blank=True)),
                (
                    "start_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "end_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("return_pct", models.CharField(blank=True, max_length=20)),
                ("is_accurate", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Analysis History",
                "verbose_name_plural": "Analysis Histories",
                "ordering": ["-created_at"],
            },
        ),
    ]
