# Generated by Django 5.1 on 2026-01-10 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_agent", "0002_analysishistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("risk_tolerance", models.CharField(default="moderate", max_length=50)),
                (
                    "investment_horizon",
                    models.CharField(default="medium-term", max_length=50),
                ),
                ("preferred_sectors", models.JSONField(blank=True, default=list)),
                ("avoided_sectors", models.JSONField(blank=True, default=list)),
                ("raw_text", models.TextField(blank=True, null=True)),
                ("chat_history", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investment_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Investment Profile",
                "verbose_name_plural": "Investment Profiles",
            },
        ),
    ]
