# Generated by Django 5.1 on 2026-01-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_agent", "0003_add_investment_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="investmentprofile",
            name="custom_instructions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="investmentprofile",
            name="investment_style",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
