# Generated by Django 5.1 on 2026-01-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_agent", "0004_add_style_and_custom"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysishistory",
            name="news_analysis",
            field=models.TextField(blank=True),
        ),
    ]
