# Generated by Django 5.1 on 2026-01-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_agent", "0005_add_news_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysishistory",
            name="end_date",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="analysishistory",
            name="start_date",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
