# Generated by Django 4.2.6 on 2024-01-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaumMovies',
            fields=[
                ('movieid', models.AutoField(db_column='movieId', primary_key=True, serialize=False)),
                ('titleko', models.CharField(blank=True, db_column='titleKo', max_length=100, null=True)),
                ('titleen', models.CharField(blank=True, db_column='titleEn', max_length=100, null=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('cast', models.CharField(blank=True, max_length=10000, null=True)),
                ('mainpageurl', models.TextField(blank=True, db_column='mainPageUrl', null=True)),
                ('posterurl', models.TextField(blank=True, db_column='posterUrl', null=True)),
                ('numofsiteratings', models.IntegerField(blank=True, db_column='numOfSiteRatings', null=True)),
            ],
            options={
                'db_table': 'daum_movies',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='WatchedMovie',
        ),
    ]
